package com.zte.ums.smartsight.policy.domain.model;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by root on 11/23/16.
 */
public class EventTypeMap {


    public static Map<String, Integer> getEventTypeMap() {
        Map<String, Integer> eventTypeMap = new HashMap<String, Integer>();
        eventTypeMap.put("CALLS_HEAVY", 1);
        eventTypeMap.put("APP_CALLHEAVY_WARNING", 10011);
        eventTypeMap.put("APP_CALLHEAVY_CRITICAL", 10012);
        eventTypeMap.put("APP_CALLHEAVY_NORMAL", 10010);
        eventTypeMap.put("APP_CALLOVERBASELINE_WARNING", 10021);
        eventTypeMap.put("APP_CALLOVERBASELINE_CRITICAL", 10022);
        eventTypeMap.put("APP_CALLOVERBASELINE_NORMAL", 10020);
        eventTypeMap.put("APP_ERRORHEAVY_WARNING", 10031);
        eventTypeMap.put("APP_ERRORHEAVY_CRITICAL", 10032);
        eventTypeMap.put("APP_ERRORHEAVY_NORMAL", 10030);
        eventTypeMap.put("APP_ERROROVERBASELINE_WARNING", 10041);
        eventTypeMap.put("APP_ERROROVERBASELINE_CRITICAL", 10042);
        eventTypeMap.put("APP_ERROROVERBASELINE_NORMAL", 10040);
        eventTypeMap.put("APP_ERRORRATIOTOOHIGH_WARNING", 10051);
        eventTypeMap.put("APP_ERRORRATIOTOOHIGH_CRITICAL", 10052);
        eventTypeMap.put("APP_ERRORRATIOTOOHIGH_NORMAL", 10050);
        eventTypeMap.put("APP_ERRORRATIOOVERBASELINE_WARNING", 10061);
        eventTypeMap.put("APP_ERRORRATIOOVERBASELINE_CRITICAL", 10062);
        eventTypeMap.put("APP_ERRORRATIOOVERBASELINE_NORMAL", 10060);
        eventTypeMap.put("APP_RESPONSETIMETOOLONG_WARNING", 10071);
        eventTypeMap.put("APP_RESPONSETIMETOOLONG_CRITICAL", 10072);
        eventTypeMap.put("APP_RESPONSETIMETOOLONG_NORMAL", 10070);
        eventTypeMap.put("APP_RESPONSETIMEOVERBASELINE_WARNING", 10081);
        eventTypeMap.put("APP_RESPONSETIMEOVERBASELINE_CRITICAL", 10082);
        eventTypeMap.put("APP_RESPONSETIMEOVERBASELINE_NORMAL", 10080);
        eventTypeMap.put("SERVICE_CALLHEAVY_WARNING", 20011);
        eventTypeMap.put("SERVICE_CALLHEAVY_CRITICAL", 20012);
        eventTypeMap.put("SERVICE_CALLHEAVY_NORMAL", 20010);
        eventTypeMap.put("SERVICE_CALLOVERBASELINE_WARNING", 20021);
        eventTypeMap.put("SERVICE_CALLOVERBASELINE_CRITICAL", 20022);
        eventTypeMap.put("SERVICE_CALLOVERBASELINE_NORMAL", 20020);
        eventTypeMap.put("SERVICE_ERRORHEAVY_WARNING", 20031);
        eventTypeMap.put("SERVICE_ERRORHEAVY_CRITICAL", 20032);
        eventTypeMap.put("SERVICE_ERRORHEAVY_NORMAL", 20030);
        eventTypeMap.put("SERVICE_ERROROVERBASELINE_WARNING", 20041);
        eventTypeMap.put("SERVICE_ERROROVERBASELINE_CRITICAL", 20042);
        eventTypeMap.put("SERVICE_ERROROVERBASELINE_NORMAL", 20040);
        eventTypeMap.put("SERVICE_ERRORRATIOTOOHIGH_WARNING", 20051);
        eventTypeMap.put("SERVICE_ERRORRATIOTOOHIGH_CRITICAL", 20052);
        eventTypeMap.put("SERVICE_ERRORRATIOTOOHIGH_NORMAL", 20050);
        eventTypeMap.put("SERVICE_ERRORRATIOOVERBASELINE_WARNING", 20061);
        eventTypeMap.put("SERVICE_ERRORRATIOOVERBASELINE_CRITICAL", 20062);
        eventTypeMap.put("SERVICE_ERRORRATIOOVERBASELINE_NORMAL", 20060);
        eventTypeMap.put("SERVICE_RESPONSETIMETOOLONG_WARNING", 20071);
        eventTypeMap.put("SERVICE_RESPONSETIMETOOLONG_CRITICAL", 20072);
        eventTypeMap.put("SERVICE_RESPONSETIMETOOLONG_NORMAL", 20070);
        eventTypeMap.put("SERVICE_RESPONSETIMEOVERBASELINE_WARNING", 20081);
        eventTypeMap.put("SERVICE_RESPONSETIMEOVERBASELINE_CRITICAL", 20082);
        eventTypeMap.put("SERVICE_RESPONSETIMEOVERBASELINE_NORMAL", 20080);
        eventTypeMap.put("INSTANCE_CALLHEAVY_WARNING", 30011);
        eventTypeMap.put("INSTANCE_CALLHEAVY_CRITICAL", 30012);
        eventTypeMap.put("INSTANCE_CALLHEAVY_NORMAL", 30010);
        eventTypeMap.put("INSTANCE_CALLOVERBASELINE_WARNING", 30021);
        eventTypeMap.put("INSTANCE_CALLOVERBASELINE_CRITICAL", 30022);
        eventTypeMap.put("INSTANCE_CALLOVERBASELINE_NORMAL", 30020);
        eventTypeMap.put("INSTANCE_ERRORHEAVY_WARNING", 30031);
        eventTypeMap.put("INSTANCE_ERRORHEAVY_CRITICAL", 30032);
        eventTypeMap.put("INSTANCE_ERRORHEAVY_NORMAL", 30030);
        eventTypeMap.put("INSTANCE_ERROROVERBASELINE_WARNING", 30041);
        eventTypeMap.put("INSTANCE_ERROROVERBASELINE_CRITICAL", 30042);
        eventTypeMap.put("INSTANCE_ERROROVERBASELINE_NORMAL", 30040);
        eventTypeMap.put("INSTANCE_ERRORRATIOTOOHIGH_WARNING", 30051);
        eventTypeMap.put("INSTANCE_ERRORRATIOTOOHIGH_CRITICAL", 30052);
        eventTypeMap.put("INSTANCE_ERRORRATIOTOOHIGH_NORMAL", 30050);
        eventTypeMap.put("INSTANCE_ERRORRATIOOVERBASELINE_WARNING", 30061);
        eventTypeMap.put("INSTANCE_ERRORRATIOOVERBASELINE_CRITICAL", 30062);
        eventTypeMap.put("INSTANCE_ERRORRATIOOVERBASELINE_NORMAL", 30060);
        eventTypeMap.put("INSTANCE_RESPONSETIMETOOLONG_WARNING", 30071);
        eventTypeMap.put("INSTANCE_RESPONSETIMETOOLONG_CRITICAL", 30072);
        eventTypeMap.put("INSTANCE_RESPONSETIMETOOLONG_NORMAL", 30070);
        eventTypeMap.put("INSTANCE_RESPONSETIMEOVERBASELINE_WARNING", 30081);
        eventTypeMap.put("INSTANCE_RESPONSETIMEOVERBASELINE_CRITICAL", 30082);
        eventTypeMap.put("INSTANCE_RESPONSETIMEOVERBASELINE_NORMAL", 30080);

        eventTypeMap.put("TRANSACTION_CALLHEAVY_WARNING", 40011);
        eventTypeMap.put("TRANSACTION_CALLHEAVY_CRITICAL", 40012);
        eventTypeMap.put("TRANSACTION_CALLHEAVY_NORMAL", 40010);
        eventTypeMap.put("TRANSACTION_CALLOVERBASELINE_WARNING", 40021);
        eventTypeMap.put("TRANSACTION_CALLOVERBASELINE_CRITICAL", 40022);
        eventTypeMap.put("TRANSACTION_CALLOVERBASELINE_NORMAL", 40020);
        eventTypeMap.put("TRANSACTION_ERRORHEAVY_WARNING", 40031);
        eventTypeMap.put("TRANSACTION_ERRORHEAVY_CRITICAL", 40032);
        eventTypeMap.put("TRANSACTION_ERRORHEAVY_NORMAL", 40030);
        eventTypeMap.put("TRANSACTION_ERROROVERBASELINE_WARNING", 40041);
        eventTypeMap.put("TRANSACTION_ERROROVERBASELINE_CRITICAL", 40042);
        eventTypeMap.put("TRANSACTION_ERROROVERBASELINE_NORMAL", 40040);
        eventTypeMap.put("TRANSACTION_ERRORRATIOTOOHIGH_WARNING", 40051);
        eventTypeMap.put("TRANSACTION_ERRORRATIOTOOHIGH_CRITICAL", 40052);
        eventTypeMap.put("TRANSACTION_ERRORRATIOTOOHIGH_NORMAL", 40050);
        eventTypeMap.put("TRANSACTION_ERRORRATIOOVERBASELINE_WARNING", 40061);
        eventTypeMap.put("TRANSACTION_ERRORRATIOOVERBASELINE_CRITICAL", 40062);
        eventTypeMap.put("TRANSACTION_ERRORRATIOOVERBASELINE_NORMAL", 40060);
        eventTypeMap.put("TRANSACTION_RESPONSETIMETOOLONG_WARNING", 40071);
        eventTypeMap.put("TRANSACTION_RESPONSETIMETOOLONG_CRITICAL", 40072);
        eventTypeMap.put("TRANSACTION_RESPONSETIMETOOLONG_NORMAL", 40070);
        eventTypeMap.put("TRANSACTION_RESPONSETIMEOVERBASELINE_WARNING", 40081);
        eventTypeMap.put("TRANSACTION_RESPONSETIMEOVERBASELINE_CRITICAL", 40082);
        eventTypeMap.put("TRANSACTION_RESPONSETIMEOVERBASELINE_NORMAL", 40080);

        eventTypeMap.put("HOST_JVMHEAPUSAGEEXCEPTION_WARNING", 50091);
        eventTypeMap.put("HOST_JVMHEAPUSAGEEXCEPTION_CRITICAL", 50092);
        eventTypeMap.put("HOST_JVMHEAPUSAGEEXCEPTION_NORMAL", 50090);
        eventTypeMap.put("HOST_GCTIMEEXCEPTION_WARNING", 50101);
        eventTypeMap.put("HOST_GCTIMEEXCEPTION_CRITICAL", 50102);
        eventTypeMap.put("HOST_GCTIMEEXCEPTION_NORMAL", 50100);
        eventTypeMap.put("HOST_GCFREQUENCYEXCEPTION_WARNING", 50111);
        eventTypeMap.put("HOST_GCFREQUENCYEXCEPTION_CRITICAL", 50112);
        eventTypeMap.put("HOST_GCFREQUENCYEXCEPTION_NORMAL", 50110);
        eventTypeMap.put("HOST_CPUUSAGEEXCEPTION_WARNING", 50121);
        eventTypeMap.put("HOST_CPUUSAGEEXCEPTION_CRITICAL", 50122);
        eventTypeMap.put("HOST_CPUUSAGEEXCEPTION_NORMAL", 50120);
        eventTypeMap.put("HOST_MEMORYUSAGEEXCEPTION_WARNING", 50131);
        eventTypeMap.put("HOST_MEMORYUSAGEEXCEPTION_CRITICAL", 50132);
        eventTypeMap.put("HOST_MEMORYUSAGEEXCEPTION_NORMAL", 50130);
        eventTypeMap.put("HOST_DISKIOEXCEPTION_WARNING", 50141);
        eventTypeMap.put("HOST_DISKIOEXCEPTION_CRITICAL", 50142);
        eventTypeMap.put("HOST_DISKIOEXCEPTION_NORMAL", 50140);
        eventTypeMap.put("HOST_NETWORKIOEXCEPTION_WARNING", 50151);
        eventTypeMap.put("HOST_NETWORKIOEXCEPTION_CRITICAL", 50152);
        eventTypeMap.put("HOST_NETWORKIOEXCEPTION_NORMAL", 50150);

        eventTypeMap.put("DB_DBOVERLOAD_WARNING", 60161);
        eventTypeMap.put("DB_DBOVERLOAD_CRITICAL", 60162);
        eventTypeMap.put("DB_DBOVERLOAD_NORMAL", 60160);
        eventTypeMap.put("DB_TOOMANYDBCONNECTIONS_WARNING", 60171);
        eventTypeMap.put("DB_TOOMANYDBCONNECTIONS_CRITICAL", 60172);
        eventTypeMap.put("DB_TOOMANYDBCONNECTIONS_NORMAL", 60170);
        eventTypeMap.put("DB_TIMESPENTINDBEXCEPTION_WARNING", 60181);
        eventTypeMap.put("DB_TIMESPENTINDBEXCEPTION_CRITICAL", 60182);
        eventTypeMap.put("DB_TIMESPENTINDBEXCEPTION_NORMAL", 60180);


        return eventTypeMap;
    }

    public static Map<Integer, String> getEventTypeToEventMap() {
        Map<Integer, String> eventTypeMap = new HashMap<Integer, String>();
        eventTypeMap.put(1, "CALLS_HEAVY");
        eventTypeMap.put(10011, "APP_CALLHEAVY_WARNING");
        eventTypeMap.put(10012, "APP_CALLHEAVY_CRITICAL");
        eventTypeMap.put(10010, "APP_CALLHEAVY_NORMAL");
        eventTypeMap.put(10021, "APP_CALLOVERBASELINE_WARNING");
        eventTypeMap.put(10022, "APP_CALLOVERBASELINE_CRITICAL");
        eventTypeMap.put(10020, "APP_CALLOVERBASELINE_NORMAL");
        eventTypeMap.put(10031, "APP_ERRORHEAVY_WARNING");
        eventTypeMap.put(10032, "APP_ERRORHEAVY_CRITICAL");
        eventTypeMap.put(10030, "APP_ERRORHEAVY_NORMAL");
        eventTypeMap.put(10041, "APP_ERROROVERBASELINE_WARNING");
        eventTypeMap.put(10042, "APP_ERROROVERBASELINE_CRITICAL");
        eventTypeMap.put(10040, "APP_ERROROVERBASELINE_NORMAL");
        eventTypeMap.put(10051, "APP_ERRORRATIOTOOHIGH_WARNING");
        eventTypeMap.put(10052, "APP_ERRORRATIOTOOHIGH_CRITICAL");
        eventTypeMap.put(10050, "APP_ERRORRATIOTOOHIGH_NORMAL");
        eventTypeMap.put(10061, "APP_ERRORRATIOOVERBASELINE_WARNING");
        eventTypeMap.put(10062, "APP_ERRORRATIOOVERBASELINE_CRITICAL");
        eventTypeMap.put(10060, "APP_ERRORRATIOOVERBASELINE_NORMAL");
        eventTypeMap.put(10071, "APP_RESPONSETIMETOOLONG_WARNING");
        eventTypeMap.put(10072, "APP_RESPONSETIMETOOLONG_CRITICAL");
        eventTypeMap.put(10070, "APP_RESPONSETIMETOOLONG_NORMAL");
        eventTypeMap.put(10081, "APP_RESPONSETIMEOVERBASELINE_WARNING");
        eventTypeMap.put(10082, "APP_RESPONSETIMEOVERBASELINE_CRITICAL");
        eventTypeMap.put(10080, "APP_RESPONSETIMEOVERBASELINE_NORMAL");
        eventTypeMap.put(20011, "SERVICE_CALLHEAVY_WARNING");
        eventTypeMap.put(20012, "SERVICE_CALLHEAVY_CRITICAL");
        eventTypeMap.put(20010, "SERVICE_CALLHEAVY_NORMAL");
        eventTypeMap.put(20021, "SERVICE_CALLOVERBASELINE_WARNING");
        eventTypeMap.put(20022, "SERVICE_CALLOVERBASELINE_CRITICAL");
        eventTypeMap.put(20020, "SERVICE_CALLOVERBASELINE_NORMAL");
        eventTypeMap.put(20031, "SERVICE_ERRORHEAVY_WARNING");
        eventTypeMap.put(20032, "SERVICE_ERRORHEAVY_CRITICAL");
        eventTypeMap.put(20030, "SERVICE_ERRORHEAVY_NORMAL");
        eventTypeMap.put(20041, "SERVICE_ERROROVERBASELINE_WARNING");
        eventTypeMap.put(20042, "SERVICE_ERROROVERBASELINE_CRITICAL");
        eventTypeMap.put(20040, "SERVICE_ERROROVERBASELINE_NORMAL");
        eventTypeMap.put(20051, "SERVICE_ERRORRATIOTOOHIGH_WARNING");
        eventTypeMap.put(20052, "SERVICE_ERRORRATIOTOOHIGH_CRITICAL");
        eventTypeMap.put(20050, "SERVICE_ERRORRATIOTOOHIGH_NORMAL");
        eventTypeMap.put(20061, "SERVICE_ERRORRATIOOVERBASELINE_WARNING");
        eventTypeMap.put(20062, "SERVICE_ERRORRATIOOVERBASELINE_CRITICAL");
        eventTypeMap.put(20060, "SERVICE_ERRORRATIOOVERBASELINE_NORMAL");
        eventTypeMap.put(20071, "SERVICE_RESPONSETIMETOOLONG_WARNING");
        eventTypeMap.put(20072, "SERVICE_RESPONSETIMETOOLONG_CRITICAL");
        eventTypeMap.put(20070, "SERVICE_RESPONSETIMETOOLONG_NORMAL");
        eventTypeMap.put(20081, "SERVICE_RESPONSETIMEOVERBASELINE_WARNING");
        eventTypeMap.put(20082, "SERVICE_RESPONSETIMEOVERBASELINE_CRITICAL");
        eventTypeMap.put(20080, "SERVICE_RESPONSETIMEOVERBASELINE_NORMAL");
        eventTypeMap.put(30011, "INSTANCE_CALLHEAVY_WARNING");
        eventTypeMap.put(30012, "INSTANCE_CALLHEAVY_CRITICAL");
        eventTypeMap.put(30010, "INSTANCE_CALLHEAVY_NORMAL");
        eventTypeMap.put(30021, "INSTANCE_CALLOVERBASELINE_WARNING");
        eventTypeMap.put(30022, "INSTANCE_CALLOVERBASELINE_CRITICAL");
        eventTypeMap.put(30020, "INSTANCE_CALLOVERBASELINE_NORMAL");
        eventTypeMap.put(30031, "INSTANCE_ERRORHEAVY_WARNING");
        eventTypeMap.put(30032, "INSTANCE_ERRORHEAVY_CRITICAL");
        eventTypeMap.put(30030, "INSTANCE_ERRORHEAVY_NORMAL");
        eventTypeMap.put(30041, "INSTANCE_ERROROVERBASELINE_WARNING");
        eventTypeMap.put(30042, "INSTANCE_ERROROVERBASELINE_CRITICAL");
        eventTypeMap.put(30040, "INSTANCE_ERROROVERBASELINE_NORMAL");
        eventTypeMap.put(30051, "INSTANCE_ERRORRATIOTOOHIGH_WARNING");
        eventTypeMap.put(30052, "INSTANCE_ERRORRATIOTOOHIGH_CRITICAL");
        eventTypeMap.put(30050, "INSTANCE_ERRORRATIOTOOHIGH_NORMAL");
        eventTypeMap.put(30061, "INSTANCE_ERRORRATIOOVERBASELINE_WARNING");
        eventTypeMap.put(30062, "INSTANCE_ERRORRATIOOVERBASELINE_CRITICAL");
        eventTypeMap.put(30060, "INSTANCE_ERRORRATIOOVERBASELINE_NORMAL");
        eventTypeMap.put(30071, "INSTANCE_RESPONSETIMETOOLONG_WARNING");
        eventTypeMap.put(30072, "INSTANCE_RESPONSETIMETOOLONG_CRITICAL");
        eventTypeMap.put(30070, "INSTANCE_RESPONSETIMETOOLONG_NORMAL");
        eventTypeMap.put(30081, "INSTANCE_RESPONSETIMEOVERBASELINE_WARNING");
        eventTypeMap.put(30082, "INSTANCE_RESPONSETIMEOVERBASELINE_CRITICAL");
        eventTypeMap.put(30080, "INSTANCE_RESPONSETIMEOVERBASELINE_NORMAL");

        eventTypeMap.put(40011, "TRANSACTION_CALLHEAVY_WARNING");
        eventTypeMap.put(40012, "TRANSACTION_CALLHEAVY_CRITICAL");
        eventTypeMap.put(40010, "TRANSACTION_CALLHEAVY_NORMAL");
        eventTypeMap.put(40021, "TRANSACTION_CALLOVERBASELINE_WARNING");
        eventTypeMap.put(40022, "TRANSACTION_CALLOVERBASELINE_CRITICAL");
        eventTypeMap.put(40020, "TRANSACTION_CALLOVERBASELINE_NORMAL");
        eventTypeMap.put(40031, "TRANSACTION_ERRORHEAVY_WARNING");
        eventTypeMap.put(40032, "TRANSACTION_ERRORHEAVY_CRITICAL");
        eventTypeMap.put(40030, "TRANSACTION_ERRORHEAVY_NORMAL");
        eventTypeMap.put(40041, "TRANSACTION_ERROROVERBASELINE_WARNING");
        eventTypeMap.put(40042, "TRANSACTION_ERROROVERBASELINE_CRITICAL");
        eventTypeMap.put(40040, "TRANSACTION_ERROROVERBASELINE_NORMAL");
        eventTypeMap.put(40051, "TRANSACTION_ERRORRATIOTOOHIGH_WARNING");
        eventTypeMap.put(40052, "TRANSACTION_ERRORRATIOTOOHIGH_CRITICAL");
        eventTypeMap.put(40050, "TRANSACTION_ERRORRATIOTOOHIGH_NORMAL");
        eventTypeMap.put(40061, "TRANSACTION_ERRORRATIOOVERBASELINE_WARNING");
        eventTypeMap.put(40062, "TRANSACTION_ERRORRATIOOVERBASELINE_CRITICAL");
        eventTypeMap.put(40060, "TRANSACTION_ERRORRATIOOVERBASELINE_NORMAL");
        eventTypeMap.put(40071, "TRANSACTION_RESPONSETIMETOOLONG_WARNING");
        eventTypeMap.put(40072, "TRANSACTION_RESPONSETIMETOOLONG_CRITICAL");
        eventTypeMap.put(40070, "TRANSACTION_RESPONSETIMETOOLONG_NORMAL");
        eventTypeMap.put(40081, "TRANSACTION_RESPONSETIMEOVERBASELINE_WARNING");
        eventTypeMap.put(40082, "TRANSACTION_RESPONSETIMEOVERBASELINE_CRITICAL");
        eventTypeMap.put(40080, "TRANSACTION_RESPONSETIMEOVERBASELINE_NORMAL");

        eventTypeMap.put(50091, "HOST_JVMHEAPUSAGEEXCEPTION_WARNING");
        eventTypeMap.put(50092, "HOST_JVMHEAPUSAGEEXCEPTION_CRITICAL");
        eventTypeMap.put(50090, "HOST_JVMHEAPUSAGEEXCEPTION_NORMAL");
        eventTypeMap.put(50101, "HOST_GCTIMEEXCEPTION_WARNING");
        eventTypeMap.put(50102, "HOST_GCTIMEEXCEPTION_CRITICAL");
        eventTypeMap.put(50100, "HOST_GCTIMEEXCEPTION_NORMAL");
        eventTypeMap.put(50111, "HOST_GCFREQUENCYEXCEPTION_WARNING");
        eventTypeMap.put(50112, "HOST_GCFREQUENCYEXCEPTION_CRITICAL");
        eventTypeMap.put(50110, "HOST_GCFREQUENCYEXCEPTION_NORMAL");
        eventTypeMap.put(50121, "HOST_CPUUSAGEEXCEPTION_WARNING");
        eventTypeMap.put(50122, "HOST_CPUUSAGEEXCEPTION_CRITICAL");
        eventTypeMap.put(50120, "HOST_CPUUSAGEEXCEPTION_NORMAL");
        eventTypeMap.put(50131, "HOST_MEMORYUSAGEEXCEPTION_WARNING");


        eventTypeMap.put(50132, "HOST_MEMORYUSAGEEXCEPTION_CRITICAL");
        eventTypeMap.put(50130, "HOST_MEMORYUSAGEEXCEPTION_NORMAL");
        eventTypeMap.put(50141, "HOST_DISKIOEXCEPTION_WARNING");
        eventTypeMap.put(50142, "HOST_DISKIOEXCEPTION_CRITICAL");
        eventTypeMap.put(50140, "HOST_DISKIOEXCEPTION_NORMAL");
        eventTypeMap.put(50151, "HOST_NETWORKIOEXCEPTION_WARNING");
        eventTypeMap.put(50152, "HOST_NETWORKIOEXCEPTION_CRITICAL");
        eventTypeMap.put(50150, "HOST_NETWORKIOEXCEPTION_NORMAL");

        eventTypeMap.put(60161, "DB_DBOVERLOAD_WARNING");
        eventTypeMap.put(60162, "DB_DBOVERLOAD_CRITICAL");
        eventTypeMap.put(60160, "DB_DBOVERLOAD_NORMAL");
        eventTypeMap.put(60171, "DB_TOOMANYDBCONNECTIONS_WARNING");
        eventTypeMap.put(60172, "DB_TOOMANYDBCONNECTIONS_CRITICAL");
        eventTypeMap.put(60170, "DB_TOOMANYDBCONNECTIONS_NORMAL");
        eventTypeMap.put(60181, "DB_TIMESPENTINDBEXCEPTION_WARNING");
        eventTypeMap.put(60182, "DB_TIMESPENTINDBEXCEPTION_CRITICAL");
        eventTypeMap.put(60180, "DB_TIMESPENTINDBEXCEPTION_NORMAL");


        return eventTypeMap;
    }


}
